### ISSUE TITLE
Is it possible to hide the selected items below SearchableDropdown.multiple?

### ISSUE THREAD

**Issue by raLaaaa** [icemanbsi/searchable_dropdown#124]
See my screenshot:

![image](https://user-images.githubusercontent.com/12799722/112339868-56a20400-8cc0-11eb-8424-e32bd3bc96b4.png)

I would like to hide blockchain and know-how and only show the dropdown field with the last selected item? Is that possible?
I couldnt find an attribute for this.

Thank you!

**Comment by lcuis** [comment]
Hello @raLaaaa ,

If you want to display only the last selected item, you can use the `selectedAggregateWidgetFn` for the `searchable_dropdown` or the `search_choices` plugin (example for `search_choices`):
```dart
SearchChoices.multiple(
        items: items,
        selectedItems: selectedItemsMultiDialog,
        onChanged: (value) {
          setState(() {
            selectedItemsMultiDialog = value;
          });
        },
        isExpanded: true,
        selectedAggregateWidgetFn: (List<Widget> list) {
          return (list.isNotEmpty?list.last:SizedBox.shrink());
        },
      )
```
![image](https://user-images.githubusercontent.com/32125299/112383973-1d808880-8cee-11eb-9abc-7f4ca3460441.png)
![image](https://user-images.githubusercontent.com/32125299/112384029-2e30fe80-8cee-11eb-8804-66d1e2283b54.png)


If you want to display the number of selected items instead of the selected items forboth plugins, you can use the same parameters as in below example:
```dart
SearchChoices.multiple(
        items: items,
        selectedItems: selectedItemsMultiDialog,
        onChanged: (value) {
          setState(() {
            selectedItemsMultiDialog = value;
          });
        },
        isExpanded: true,
        selectedAggregateWidgetFn: (List<Widget> list) {
          return (Text("${list.length} items selected"));
        },
      )
```
![image](https://user-images.githubusercontent.com/32125299/112384255-78b27b00-8cee-11eb-8210-6376dccfdeaf.png)

**Comment by raLaaaa** [comment]
Thank you!

**Comment by lcuis** [comment]
You’re welcome
