### ISSUE TITLE
How to change its background color dialog

### ISSUE THREAD

**Issue by kittist** [icemanbsi/searchable_dropdown#14]
I want to change its background color from white color to dark color.

**Comment by lcuis** [comment]
Hello @kittist ,

I was able to set the background to yellow on the latest version of this plugin as PR #13  with the following:
```
    return MaterialApp(
      theme:   ThemeData(
        cardColor: Colors.yellowAccent,
      ),
...
```
Here is the result within the example app:
* Dialog
![image](https://user-images.githubusercontent.com/32125299/75372891-81593780-58c9-11ea-8ac6-5a88bf036ed7.png)
* Menu
![image](https://user-images.githubusercontent.com/32125299/75372943-99c95200-58c9-11ea-82f4-087e39f51493.png)

If you need to change the card color for all cards in your `MaterialApp`, this solution is quite convenient. Otherwise, changing the background color for just one widget would probably require a change in code. Is this something that you would need or changing for all cards through theme is good enough for you?

**Comment by lcuis** [comment]
Hello @kittist ,

I just added a `menuBackgroundColor` to the next PR #16 for this plugin. (If you don't want to wait for the publication of this PR, I also implemented it on [my version of the plugin](https://pub.dev/packages/search_choices) ).

With this parameter, you can define the background color of the menu without affecting the other cards of the app.

**Comment by kittist** [comment]
I tried it in PR #16.
It works! thanks

but It would be perfect if I can change font/icon color like this 

<img width="285" alt="Screen Shot 2563-03-02 at 10 43 27" src="https://user-images.githubusercontent.com/22907538/75643850-d3f07600-5c72-11ea-9fd9-607ff9d12835.png">

**Comment by icemanbsi** [comment]
Hi @kittist  
I've published the update (thanks @lcuis ) on pub.dev.
I'll close this issue and feel free to reopen if you think this issue is not solved yet.
Thanks
