### ISSUE TITLE
Compilation failed Flutter 2.5.0

### ISSUE THREAD

**Issue by aragonet** [icemanbsi/searchable_dropdown#147]
Flutter 2.5.0 deprecated textTheme.subhead property in favor of textTheme.subtitle1.

**Comment by lcuis** [comment]
Thanks for reporting this @aragonet . Can you please let us know whether this also affects the `search_choices` plugin?

**Comment by aragonet** [comment]
It works like a charm!

(It would be great if you could add a comment in the readme for people to use search_choices)

**Comment by bondjpf** [comment]
Any way too get past this error? Can't compile either....

/C:/Flutter/.pub-cache/hosted/pub.dartlang.org/searchable_dropdown-1.1.3/lib/searchable_dropdown.dart:371:41: Error: The getter 'subhead' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/Flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subhead'.
          ? Theme.of(context).textTheme.subhead
                                        ^^^^^^^

**Comment by lcuis** [comment]
@bondjpf have you tried with the `search_choices` plugin?

**Comment by bondjpf** [comment]
Will try thanks.

**Comment by bondjpf** [comment]
> @bondjpf have you tried with the `search_choices` plugin?

Tried and it worked. No more error.
Now the problem is that when I select an item I get:

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
E/flutter (20030): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
E/flutter (20030): #0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:909:9)
E/flutter (20030): #1      State.context (package:flutter/src/widgets/framework.dart:915:6)
E/flutter (20030): #2      _SearchChoicesState.showDialogOrMenu (package:search_choices/search_choices.dart:1196:39)
E/flutter (20030): <asynchronous suspension>
E/flutter (20030): #3      _SearchChoicesState.build.<anonymous closure> (package:search_choices/search_choices.dart:1277:21)
E/flutter (20030): <asynchronous suspension>
E/flutter (20030):

**Comment by lcuis** [comment]
Hi @bondjpf ,

Great that the `search_choices` plugin compiles without any problem.

Can you please open an issue [here](https://github.com/lcuis/search_choices/issues) if your new issue relates to this plugin?

Also, can you please include a minimalist code to help me reproduce your issue?
