### ISSUE TITLE
Typeahead async search?

### ISSUE THREAD

**Issue by duzenko** [icemanbsi/searchable_dropdown#19]
How do I wire this widget to network queries returning the search results?

**Comment by lcuis** [comment]
Hello @duzenko ,

Is your request equivalent to what is mentioned in #44 ?

**Comment by duzenko** [comment]
I think so

**Comment by lcuis** [comment]
Ok, thanks for the confirmation @duzenko and thanks for raising the issue.
As the other issue was marked as "enhancement", I'll close this issue for now. I hope you don't mind.
Feel free to reopen if needed.

**Comment by lcuis** [comment]
Since version 2.0.4 and later, the `SearchChoices` plugin supports pagination and Future/network/API/webservice calls.
The example is meant to work with PHP-CRUD-API based webservice using a non-web Flutter client. However, the example can be adapted for many other situations.
https://github.com/lcuis/search_choices#single-dialog-paged-future
